### ISSUE TITLE
Review DLMF seeding programs

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF-Seeding-Project#1]
The DLMF seeding programs
https://github.com/DRMF/DRMF-Seeding-Project/blob/master/AlexDanoff/remove_excess.py
https://github.com/DRMF/DRMF-Seeding-Project/blob/master/AlexDanoff/replace_special.py
https://github.com/DRMF/DRMF-Seeding-Project/blob/master/AlexDanoff/prepare_annotations.py
need to be reviewed.
Maybe there are also automated tests that could be added.
@alexeygrigorev do you have experience with that by chance?

**Comment by HowardCohl** [comment]
@notjagan Some of these are currently being modified to work with Jagan's Python math mode code.  Have you uploaded it here yet? @physikerwelt I think we need to change of this directory the name also. What is blob? I don't think the above links work anymore.

**Comment by physikerwelt** [comment]
Sorry I have basically done what I was intending to do here... have a look at the programs and get an idea of what they are doing.
