### ISSUE TITLE
Review possible bugs

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF-Seeding-Project#17]
The automatic code inspection tool identified several (25) potential bugs
https://landscape.io/github/edward-bian/DRMF-Seeding-Project/5/messages/error
Some of them seem to be easy to fix.

**Comment by physikerwelt** [comment]
CC @DRMF/developers

**Comment by HowardCohl** [comment]
I think this should be assigned to @edward-bian  Do you agree?

**Comment by physikerwelt** [comment]
Yes. That should be relatively straight forward to fix.

**Comment by HowardCohl** [comment]
@physikerwelt @edward-bian @joonbang 

Thanks Joon!

**Comment by joonbang** [comment]
No problem!
