### ISSUE TITLE
Homogenize DLMFtex2Wiki.py and tex2Wiki

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF-Seeding-Project#41]
Make DLMFtex2Wiki.py look like tex2Wiki.
- [x] import tex2Wiki (for now)
- [x] Identify and then remove all subroutines from DLMFtex2Wiki (such as is_number) that are exactly the same in tex2Wiki.
- [x] adjust the output from mmd to xml
- [ ] remove `{\displaystyle` ... `}` wrapper
- [x] rename jsahlfkjsd -> iterations in tex2Wiki
- [ ] make `DLMF` (in `DLMFtex2Wiki`) accept 3 arguments like `readin` (in `tex2Wiki`) i.e., `ofname,glossary,mmd`
- [ ] remove all commented code such as  `#tester=open("testData.txt",'w')`
- [x] replace `wiki.write` with `append_text`
- [ ] convert `bof` `eof` to `append_revision`

You should make a commit after every step.

**Comment by HowardCohl** [comment]
I think the first task must be to make sure that the new program matches the output of both programs that were merged to obtain it.

**Comment by HowardCohl** [comment]
I don't think we should get rid of mmd.  Perhaps we should create an option to output both outputs. But this should occur after we complete the above task.

**Comment by HowardCohl** [comment]
I think the above items are way ahead of itself.

**Comment by HowardCohl** [comment]
@pwang00 @physikerwelt 

I just finished working with Moritz, and we updated the list that you should work on Philip.

**Comment by physikerwelt** [comment]
@pwang00 you removed mod_label even though that seems to be different. Can you fix that? If you have problems to fix it, you are very welcome in my office.

**Comment by physikerwelt** [comment]
@pwang00 the next time you'd like to change the task order, please discuss that in advance.

**Comment by pwang00** [comment]
I believe I changed the jsahlfkjsd -> iterations in tex2Wiki a bit too early.  Is that ok?

**Comment by physikerwelt** [comment]
@pwang00 thank you for your contributions. I'll take care of the rest.
