### ISSUE TITLE
Ensure that pull request pass automatic unit tests

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF-Seeding-Project#64]
@DRMF/developers please make sure that your pull request passes the automatic test. Currently there are 7 pull request. None of them passes the test. Passing the tests is a first prerequisite for getting your code reviewed and merged.
If you are unsure why your code does not pass the automated tests click on "Details". In most cases the displayed information will be good i ndicators why the tests fail.

**Comment by plato2000** [comment]
I think this is resolved for the most part now (for all active developers)
