### ISSUE TITLE
Talk about splitting the repository into parts for each project

### ISSUE THREAD

**Issue by plato2000** [DRMF/DRMF-Seeding-Project#77]
It was recently suggested  by @notjagan that for each subproject in the Seeding Project there should be a separate git repository. Logically, this may make more sense than keeping everything together, since development on each one is done completely separately. Since eventually, these projects will come together, each of the repositories can be added here as submodules.

This suggestion seems to make sense from a logical standpoint, but it needs to be discussed whether or not the benefits outweigh the downsides. These downsides may include the inconvenience of moving the projects out (which won't actually be so bad) and maybe there will be management issues with the split up projects. 

This issue is opened here for discussion about this problem.

**Comment by HowardCohl** [comment]
@physikerwelt Do you see any problem with this? What do you think about this?

**Comment by physikerwelt** [comment]
@HowardCohl whatever works best for the development process is fine with me.
Multiple project create a slight management overhead and will make it a litle bit more difficult to enforce best practices among several repositories.
In addition to that, I like the graphs that demonstrate that a lot of poeple are actively and continously working on the project.
https://github.com/DRMF/DRMF-Seeding-Project/graphs/contributors

However, as long as someone takes care of maitaining several repositories I'm fine with either way.

**Comment by HowardCohl** [comment]
@physikerwelt I agree. I like it too. Let's keep it like it is.
