### ISSUE TITLE
Agree on a merge policity for the DRMF-Seeding-Project

### ISSUE THREAD

**Issue by physikerwelt** [DRMF/DRMF-Seeding-Project#8]
I think in general we should use pull request instead of an open push model.
This is especially relevant for actual code that is modified by different people.
Moreover, optimally you would not self-merge your pull request and get the code reviewed by another developer.
@ILIKEFUUD @HowardCohl @svellala2001 @pwang00 @edward-bian please share your thoughts on that.

**Comment by HowardCohl** [comment]
I think it has been formally decided that has been adopted. Although the newly invited students need to be aware of this.

**Comment by physikerwelt** [comment]
@HowardCohl I created a pull request. This file will be shown automatically as help. We can extend it lter if needed.

**Comment by physikerwelt** [comment]
See https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md for an example of a really well designed contributing file. However, I currently do not want to spend time ot write such a document.

**Comment by HowardCohl** [comment]
@physikerwelt I can't recall. Has everybody we invited accepted?

**Comment by physikerwelt** [comment]
@HowardCohl this is off-topic here see https://github.com/DRMF/DRMF-Seeding-Project/issues currently only 1/4 accepted
